Lecture-7 Home work
bytekot/meal-delivery-service pull request #7
Opened 2023-12-06 15:34 UTC by bytekot

Add and connect Redux store to the app.

2023-12-07 15:30 UTC, SArchieEdu requested changes

2023-12-07 15:30 UTC, SArchieEdu commented on src/pages/restaurants-page/component.jsx
> +    const restaurantNames = useSelector(selectRestaurantNames)
лучше использовать селектор в том месте, где его данные нужны, фишка в том, что не нужно прокидывать через пропсы

2023-12-07 15:30 UTC, SArchieEdu commented on src/pages/restaurants-page/component.jsx
> +    const tabs = restaurantIds.map(id => ({ id: id, label: restaurantNames[id] }))
не нужно селектить части сущности и потом собирать их обратно в компоненте, лучше использовать подход с айдишками, либо запрашивать рестораны целиком. Подход с айдишками будет лучше

2023-12-09 12:08 UTC, bytekot commented on src/pages/restaurants-page/component.jsx
> +    const restaurantNames = useSelector(selectRestaurantNames)
Сделал так здесь, потому что компонент Tabs используется также в Restaurant для разделения вьюхи на "Menu" и "Reviews". На лекции задавал вопрос — ты ответил, что научишь, как по уму наследоваться от Tabs, позже.
Пока оставил два похожих компонента — Tabs и RestaurantTabs.

2023-12-11 15:25 UTC, merged